---
- name: To test block and rescue
  hosts: all
  tasks:
    - name: Acccess web page
      uri:
        url: http://192.168.29.69/index.html
      register: http_output
    - name: capture
      debug:
        var: http_output
