---
- name: To test block and rescue
  hosts: all
  tasks:
  - block:
    - name: Acccess web page
      win_uri:
        url: http://192.168.29.68
      register: my
    - name: Page accessible
      debug:
        msg: website is accessible
      when: my.status_code == 200
    rescue:  
    - name: Page is not accessible
      debug:
        msg: website is not accessible
      when: my.status_code != 200
      
