---
- name: Loop register test
  hosts: all
  tasks:
  - name: Executing commands and registering output in the variable "output"
    win_shell: "{{ item }}"
    loop:
      - whoami
      - hostname
    register: output
    when: inventory_hostname == '192.168.29.69'
  - name: showing the results from output variable
    debug:
      var: output
